// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aazakceyruefejeyhkbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFhemFrY2V5cnVlZmVqZXloa2JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMjA4MzUsImV4cCI6MjA3MDU5NjgzNX0.fA2KNJx6503vwVSQ8hJ1VdzOJEqVIVYhE-4Z48KS_dg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});